package com.ufgov.zc.common.pay.model;

import java.math.BigDecimal;

public class PayVoucher {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.VOUCHER_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String voucherNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.BUDGET_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String budgetId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.FROMCTRLID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String fromctrlid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.SET_YEAR
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private Short setYear;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.VOUCHER_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String voucherBillId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.AGENT_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String agentBillId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CLEAR_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String clearBillId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.ACC_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String accBillId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.EN_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String enBillId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.DAY_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String dayBillId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.EDITER_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String editerCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.RG_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String rgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.BILLTYPE_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String billtypeCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAY_MONEY
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private BigDecimal payMoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.REMARK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.IS_VALID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private Short isValid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.IS_END
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private Short isEnd;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.APPROVE_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String approveDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CREATE_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CREATE_USER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String createUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.LATEST_OP_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String latestOpDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.LATEST_OP_USER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String latestOpUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.LAST_VER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String lastVer;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PA_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String paCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAYEE_ACCOUNT_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String payeeAccountId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.AGENT_ACCOUNT_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String agentAccountId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAY_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String payDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CLEAR_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String clearDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.OLD_PAY_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String oldPayId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.HOLD1
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String hold1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.HOLD2
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String hold2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.HOLD3
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String hold3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAY_SUMMARY_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String paySummaryCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAY_SUMMARY_NAME
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String paySummaryName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAY_SUMMARY_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String paySummaryId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.DISP_ORDER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private BigDecimal dispOrder;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.GOV_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String govId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.GOV_REMARK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String govRemark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.ACCESSORY_NUMBER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private BigDecimal accessoryNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.FROMCTRLTYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String fromctrltype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.TOCTRLTYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String toctrltype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.ORIGIN_MODEL
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private Short originModel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAYEE_ACCOUNT_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String payeeAccountNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAYEE_ACCOUNT_BANK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String payeeAccountBank;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CHECK_PASSWORD
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String checkPassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.DATA_TYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String dataType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.PAYEE_ACCOUNT_NAME
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String payeeAccountName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CHECK_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String checkNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.RCID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private BigDecimal rcid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.CCID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private BigDecimal ccid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.EXCHANGE_FLAG
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String exchangeFlag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.EXCHANGE_TEXT
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String exchangeText;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.BATCH_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private String batchNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column PAY_VOUCHER.INPUT_MONEY
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    private BigDecimal inputMoney;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.ID
     *
     * @return the value of PAY_VOUCHER.ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.ID
     *
     * @param id the value for PAY_VOUCHER.ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.VOUCHER_NO
     *
     * @return the value of PAY_VOUCHER.VOUCHER_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.VOUCHER_NO
     *
     * @param voucherNo the value for PAY_VOUCHER.VOUCHER_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.BUDGET_ID
     *
     * @return the value of PAY_VOUCHER.BUDGET_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getBudgetId() {
        return budgetId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.BUDGET_ID
     *
     * @param budgetId the value for PAY_VOUCHER.BUDGET_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setBudgetId(String budgetId) {
        this.budgetId = budgetId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.FROMCTRLID
     *
     * @return the value of PAY_VOUCHER.FROMCTRLID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getFromctrlid() {
        return fromctrlid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.FROMCTRLID
     *
     * @param fromctrlid the value for PAY_VOUCHER.FROMCTRLID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setFromctrlid(String fromctrlid) {
        this.fromctrlid = fromctrlid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.SET_YEAR
     *
     * @return the value of PAY_VOUCHER.SET_YEAR
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public Short getSetYear() {
        return setYear;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.SET_YEAR
     *
     * @param setYear the value for PAY_VOUCHER.SET_YEAR
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setSetYear(Short setYear) {
        this.setYear = setYear;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.VOUCHER_BILL_ID
     *
     * @return the value of PAY_VOUCHER.VOUCHER_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getVoucherBillId() {
        return voucherBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.VOUCHER_BILL_ID
     *
     * @param voucherBillId the value for PAY_VOUCHER.VOUCHER_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setVoucherBillId(String voucherBillId) {
        this.voucherBillId = voucherBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.AGENT_BILL_ID
     *
     * @return the value of PAY_VOUCHER.AGENT_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getAgentBillId() {
        return agentBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.AGENT_BILL_ID
     *
     * @param agentBillId the value for PAY_VOUCHER.AGENT_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setAgentBillId(String agentBillId) {
        this.agentBillId = agentBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CLEAR_BILL_ID
     *
     * @return the value of PAY_VOUCHER.CLEAR_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getClearBillId() {
        return clearBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CLEAR_BILL_ID
     *
     * @param clearBillId the value for PAY_VOUCHER.CLEAR_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setClearBillId(String clearBillId) {
        this.clearBillId = clearBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.ACC_BILL_ID
     *
     * @return the value of PAY_VOUCHER.ACC_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getAccBillId() {
        return accBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.ACC_BILL_ID
     *
     * @param accBillId the value for PAY_VOUCHER.ACC_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setAccBillId(String accBillId) {
        this.accBillId = accBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.EN_BILL_ID
     *
     * @return the value of PAY_VOUCHER.EN_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getEnBillId() {
        return enBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.EN_BILL_ID
     *
     * @param enBillId the value for PAY_VOUCHER.EN_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setEnBillId(String enBillId) {
        this.enBillId = enBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.DAY_BILL_ID
     *
     * @return the value of PAY_VOUCHER.DAY_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getDayBillId() {
        return dayBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.DAY_BILL_ID
     *
     * @param dayBillId the value for PAY_VOUCHER.DAY_BILL_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setDayBillId(String dayBillId) {
        this.dayBillId = dayBillId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.EDITER_CODE
     *
     * @return the value of PAY_VOUCHER.EDITER_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getEditerCode() {
        return editerCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.EDITER_CODE
     *
     * @param editerCode the value for PAY_VOUCHER.EDITER_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setEditerCode(String editerCode) {
        this.editerCode = editerCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.RG_CODE
     *
     * @return the value of PAY_VOUCHER.RG_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getRgCode() {
        return rgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.RG_CODE
     *
     * @param rgCode the value for PAY_VOUCHER.RG_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setRgCode(String rgCode) {
        this.rgCode = rgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.BILLTYPE_CODE
     *
     * @return the value of PAY_VOUCHER.BILLTYPE_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getBilltypeCode() {
        return billtypeCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.BILLTYPE_CODE
     *
     * @param billtypeCode the value for PAY_VOUCHER.BILLTYPE_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setBilltypeCode(String billtypeCode) {
        this.billtypeCode = billtypeCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAY_MONEY
     *
     * @return the value of PAY_VOUCHER.PAY_MONEY
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public BigDecimal getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAY_MONEY
     *
     * @param payMoney the value for PAY_VOUCHER.PAY_MONEY
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.REMARK
     *
     * @return the value of PAY_VOUCHER.REMARK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.REMARK
     *
     * @param remark the value for PAY_VOUCHER.REMARK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.IS_VALID
     *
     * @return the value of PAY_VOUCHER.IS_VALID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.IS_VALID
     *
     * @param isValid the value for PAY_VOUCHER.IS_VALID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setIsValid(Short isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.IS_END
     *
     * @return the value of PAY_VOUCHER.IS_END
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public Short getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.IS_END
     *
     * @param isEnd the value for PAY_VOUCHER.IS_END
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setIsEnd(Short isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.APPROVE_DATE
     *
     * @return the value of PAY_VOUCHER.APPROVE_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.APPROVE_DATE
     *
     * @param approveDate the value for PAY_VOUCHER.APPROVE_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setApproveDate(String approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CREATE_DATE
     *
     * @return the value of PAY_VOUCHER.CREATE_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CREATE_DATE
     *
     * @param createDate the value for PAY_VOUCHER.CREATE_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CREATE_USER
     *
     * @return the value of PAY_VOUCHER.CREATE_USER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CREATE_USER
     *
     * @param createUser the value for PAY_VOUCHER.CREATE_USER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.LATEST_OP_DATE
     *
     * @return the value of PAY_VOUCHER.LATEST_OP_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getLatestOpDate() {
        return latestOpDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.LATEST_OP_DATE
     *
     * @param latestOpDate the value for PAY_VOUCHER.LATEST_OP_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setLatestOpDate(String latestOpDate) {
        this.latestOpDate = latestOpDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.LATEST_OP_USER
     *
     * @return the value of PAY_VOUCHER.LATEST_OP_USER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getLatestOpUser() {
        return latestOpUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.LATEST_OP_USER
     *
     * @param latestOpUser the value for PAY_VOUCHER.LATEST_OP_USER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setLatestOpUser(String latestOpUser) {
        this.latestOpUser = latestOpUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.LAST_VER
     *
     * @return the value of PAY_VOUCHER.LAST_VER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getLastVer() {
        return lastVer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.LAST_VER
     *
     * @param lastVer the value for PAY_VOUCHER.LAST_VER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setLastVer(String lastVer) {
        this.lastVer = lastVer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PA_CODE
     *
     * @return the value of PAY_VOUCHER.PA_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPaCode() {
        return paCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PA_CODE
     *
     * @param paCode the value for PAY_VOUCHER.PA_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPaCode(String paCode) {
        this.paCode = paCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_ID
     *
     * @return the value of PAY_VOUCHER.PAYEE_ACCOUNT_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPayeeAccountId() {
        return payeeAccountId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_ID
     *
     * @param payeeAccountId the value for PAY_VOUCHER.PAYEE_ACCOUNT_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPayeeAccountId(String payeeAccountId) {
        this.payeeAccountId = payeeAccountId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.AGENT_ACCOUNT_ID
     *
     * @return the value of PAY_VOUCHER.AGENT_ACCOUNT_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getAgentAccountId() {
        return agentAccountId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.AGENT_ACCOUNT_ID
     *
     * @param agentAccountId the value for PAY_VOUCHER.AGENT_ACCOUNT_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setAgentAccountId(String agentAccountId) {
        this.agentAccountId = agentAccountId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAY_DATE
     *
     * @return the value of PAY_VOUCHER.PAY_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAY_DATE
     *
     * @param payDate the value for PAY_VOUCHER.PAY_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CLEAR_DATE
     *
     * @return the value of PAY_VOUCHER.CLEAR_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getClearDate() {
        return clearDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CLEAR_DATE
     *
     * @param clearDate the value for PAY_VOUCHER.CLEAR_DATE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setClearDate(String clearDate) {
        this.clearDate = clearDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.OLD_PAY_ID
     *
     * @return the value of PAY_VOUCHER.OLD_PAY_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getOldPayId() {
        return oldPayId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.OLD_PAY_ID
     *
     * @param oldPayId the value for PAY_VOUCHER.OLD_PAY_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setOldPayId(String oldPayId) {
        this.oldPayId = oldPayId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.HOLD1
     *
     * @return the value of PAY_VOUCHER.HOLD1
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getHold1() {
        return hold1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.HOLD1
     *
     * @param hold1 the value for PAY_VOUCHER.HOLD1
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setHold1(String hold1) {
        this.hold1 = hold1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.HOLD2
     *
     * @return the value of PAY_VOUCHER.HOLD2
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getHold2() {
        return hold2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.HOLD2
     *
     * @param hold2 the value for PAY_VOUCHER.HOLD2
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setHold2(String hold2) {
        this.hold2 = hold2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.HOLD3
     *
     * @return the value of PAY_VOUCHER.HOLD3
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getHold3() {
        return hold3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.HOLD3
     *
     * @param hold3 the value for PAY_VOUCHER.HOLD3
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setHold3(String hold3) {
        this.hold3 = hold3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAY_SUMMARY_CODE
     *
     * @return the value of PAY_VOUCHER.PAY_SUMMARY_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPaySummaryCode() {
        return paySummaryCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAY_SUMMARY_CODE
     *
     * @param paySummaryCode the value for PAY_VOUCHER.PAY_SUMMARY_CODE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPaySummaryCode(String paySummaryCode) {
        this.paySummaryCode = paySummaryCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAY_SUMMARY_NAME
     *
     * @return the value of PAY_VOUCHER.PAY_SUMMARY_NAME
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPaySummaryName() {
        return paySummaryName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAY_SUMMARY_NAME
     *
     * @param paySummaryName the value for PAY_VOUCHER.PAY_SUMMARY_NAME
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPaySummaryName(String paySummaryName) {
        this.paySummaryName = paySummaryName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAY_SUMMARY_ID
     *
     * @return the value of PAY_VOUCHER.PAY_SUMMARY_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPaySummaryId() {
        return paySummaryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAY_SUMMARY_ID
     *
     * @param paySummaryId the value for PAY_VOUCHER.PAY_SUMMARY_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPaySummaryId(String paySummaryId) {
        this.paySummaryId = paySummaryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.DISP_ORDER
     *
     * @return the value of PAY_VOUCHER.DISP_ORDER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public BigDecimal getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.DISP_ORDER
     *
     * @param dispOrder the value for PAY_VOUCHER.DISP_ORDER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setDispOrder(BigDecimal dispOrder) {
        this.dispOrder = dispOrder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.GOV_ID
     *
     * @return the value of PAY_VOUCHER.GOV_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getGovId() {
        return govId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.GOV_ID
     *
     * @param govId the value for PAY_VOUCHER.GOV_ID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setGovId(String govId) {
        this.govId = govId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.GOV_REMARK
     *
     * @return the value of PAY_VOUCHER.GOV_REMARK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getGovRemark() {
        return govRemark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.GOV_REMARK
     *
     * @param govRemark the value for PAY_VOUCHER.GOV_REMARK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setGovRemark(String govRemark) {
        this.govRemark = govRemark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.ACCESSORY_NUMBER
     *
     * @return the value of PAY_VOUCHER.ACCESSORY_NUMBER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public BigDecimal getAccessoryNumber() {
        return accessoryNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.ACCESSORY_NUMBER
     *
     * @param accessoryNumber the value for PAY_VOUCHER.ACCESSORY_NUMBER
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setAccessoryNumber(BigDecimal accessoryNumber) {
        this.accessoryNumber = accessoryNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.FROMCTRLTYPE
     *
     * @return the value of PAY_VOUCHER.FROMCTRLTYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getFromctrltype() {
        return fromctrltype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.FROMCTRLTYPE
     *
     * @param fromctrltype the value for PAY_VOUCHER.FROMCTRLTYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setFromctrltype(String fromctrltype) {
        this.fromctrltype = fromctrltype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.TOCTRLTYPE
     *
     * @return the value of PAY_VOUCHER.TOCTRLTYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getToctrltype() {
        return toctrltype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.TOCTRLTYPE
     *
     * @param toctrltype the value for PAY_VOUCHER.TOCTRLTYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setToctrltype(String toctrltype) {
        this.toctrltype = toctrltype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.ORIGIN_MODEL
     *
     * @return the value of PAY_VOUCHER.ORIGIN_MODEL
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public Short getOriginModel() {
        return originModel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.ORIGIN_MODEL
     *
     * @param originModel the value for PAY_VOUCHER.ORIGIN_MODEL
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setOriginModel(Short originModel) {
        this.originModel = originModel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_NO
     *
     * @return the value of PAY_VOUCHER.PAYEE_ACCOUNT_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPayeeAccountNo() {
        return payeeAccountNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_NO
     *
     * @param payeeAccountNo the value for PAY_VOUCHER.PAYEE_ACCOUNT_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPayeeAccountNo(String payeeAccountNo) {
        this.payeeAccountNo = payeeAccountNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_BANK
     *
     * @return the value of PAY_VOUCHER.PAYEE_ACCOUNT_BANK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPayeeAccountBank() {
        return payeeAccountBank;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_BANK
     *
     * @param payeeAccountBank the value for PAY_VOUCHER.PAYEE_ACCOUNT_BANK
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPayeeAccountBank(String payeeAccountBank) {
        this.payeeAccountBank = payeeAccountBank;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CHECK_PASSWORD
     *
     * @return the value of PAY_VOUCHER.CHECK_PASSWORD
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getCheckPassword() {
        return checkPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CHECK_PASSWORD
     *
     * @param checkPassword the value for PAY_VOUCHER.CHECK_PASSWORD
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setCheckPassword(String checkPassword) {
        this.checkPassword = checkPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.DATA_TYPE
     *
     * @return the value of PAY_VOUCHER.DATA_TYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.DATA_TYPE
     *
     * @param dataType the value for PAY_VOUCHER.DATA_TYPE
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_NAME
     *
     * @return the value of PAY_VOUCHER.PAYEE_ACCOUNT_NAME
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getPayeeAccountName() {
        return payeeAccountName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.PAYEE_ACCOUNT_NAME
     *
     * @param payeeAccountName the value for PAY_VOUCHER.PAYEE_ACCOUNT_NAME
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setPayeeAccountName(String payeeAccountName) {
        this.payeeAccountName = payeeAccountName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CHECK_NO
     *
     * @return the value of PAY_VOUCHER.CHECK_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getCheckNo() {
        return checkNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CHECK_NO
     *
     * @param checkNo the value for PAY_VOUCHER.CHECK_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setCheckNo(String checkNo) {
        this.checkNo = checkNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.RCID
     *
     * @return the value of PAY_VOUCHER.RCID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public BigDecimal getRcid() {
        return rcid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.RCID
     *
     * @param rcid the value for PAY_VOUCHER.RCID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setRcid(BigDecimal rcid) {
        this.rcid = rcid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.CCID
     *
     * @return the value of PAY_VOUCHER.CCID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public BigDecimal getCcid() {
        return ccid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.CCID
     *
     * @param ccid the value for PAY_VOUCHER.CCID
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setCcid(BigDecimal ccid) {
        this.ccid = ccid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.EXCHANGE_FLAG
     *
     * @return the value of PAY_VOUCHER.EXCHANGE_FLAG
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getExchangeFlag() {
        return exchangeFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.EXCHANGE_FLAG
     *
     * @param exchangeFlag the value for PAY_VOUCHER.EXCHANGE_FLAG
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setExchangeFlag(String exchangeFlag) {
        this.exchangeFlag = exchangeFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.EXCHANGE_TEXT
     *
     * @return the value of PAY_VOUCHER.EXCHANGE_TEXT
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getExchangeText() {
        return exchangeText;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.EXCHANGE_TEXT
     *
     * @param exchangeText the value for PAY_VOUCHER.EXCHANGE_TEXT
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setExchangeText(String exchangeText) {
        this.exchangeText = exchangeText;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.BATCH_NO
     *
     * @return the value of PAY_VOUCHER.BATCH_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.BATCH_NO
     *
     * @param batchNo the value for PAY_VOUCHER.BATCH_NO
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column PAY_VOUCHER.INPUT_MONEY
     *
     * @return the value of PAY_VOUCHER.INPUT_MONEY
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public BigDecimal getInputMoney() {
        return inputMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column PAY_VOUCHER.INPUT_MONEY
     *
     * @param inputMoney the value for PAY_VOUCHER.INPUT_MONEY
     *
     * @abatorgenerated Tue Jul 31 07:18:21 GMT 2012
     */
    public void setInputMoney(BigDecimal inputMoney) {
        this.inputMoney = inputMoney;
    }
}