package com.ufgov.zc.common.console.model;

import java.math.BigDecimal;

public class SysUserRoleRule {

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ROLE_RULE.ROLE_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  private BigDecimal roleId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ROLE_RULE.USER_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  private String userId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ROLE_RULE.RULE_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  private BigDecimal ruleId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ROLE_RULE.IS_DEFINED
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  private Short isDefined;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ROLE_RULE.SET_YEAR
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  private Short setYear;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ROLE_RULE.LAST_VER
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  private String lastVer;

  private String rgCode;

  public String getRgCode() {
    return rgCode;
  }

  public void setRgCode(String rgCode) {
    this.rgCode = rgCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ROLE_RULE.ROLE_ID
   *
   * @return the value of SYS_USER_ROLE_RULE.ROLE_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public BigDecimal getRoleId() {
    return roleId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ROLE_RULE.ROLE_ID
   *
   * @param roleId the value for SYS_USER_ROLE_RULE.ROLE_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public void setRoleId(BigDecimal roleId) {
    this.roleId = roleId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ROLE_RULE.USER_ID
   *
   * @return the value of SYS_USER_ROLE_RULE.USER_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ROLE_RULE.USER_ID
   *
   * @param userId the value for SYS_USER_ROLE_RULE.USER_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ROLE_RULE.RULE_ID
   *
   * @return the value of SYS_USER_ROLE_RULE.RULE_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public BigDecimal getRuleId() {
    return ruleId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ROLE_RULE.RULE_ID
   *
   * @param ruleId the value for SYS_USER_ROLE_RULE.RULE_ID
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public void setRuleId(BigDecimal ruleId) {
    this.ruleId = ruleId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ROLE_RULE.IS_DEFINED
   *
   * @return the value of SYS_USER_ROLE_RULE.IS_DEFINED
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public Short getIsDefined() {
    return isDefined;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ROLE_RULE.IS_DEFINED
   *
   * @param isDefined the value for SYS_USER_ROLE_RULE.IS_DEFINED
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public void setIsDefined(Short isDefined) {
    this.isDefined = isDefined;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ROLE_RULE.SET_YEAR
   *
   * @return the value of SYS_USER_ROLE_RULE.SET_YEAR
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public Short getSetYear() {
    return setYear;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ROLE_RULE.SET_YEAR
   *
   * @param setYear the value for SYS_USER_ROLE_RULE.SET_YEAR
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public void setSetYear(Short setYear) {
    this.setYear = setYear;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ROLE_RULE.LAST_VER
   *
   * @return the value of SYS_USER_ROLE_RULE.LAST_VER
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public String getLastVer() {
    return lastVer;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ROLE_RULE.LAST_VER
   *
   * @param lastVer the value for SYS_USER_ROLE_RULE.LAST_VER
   *
   * @abatorgenerated Tue May 08 07:06:01 GMT 2012
   */
  public void setLastVer(String lastVer) {
    this.lastVer = lastVer;
  }
}