package com.ufgov.zc.common.console.model;

public class SysUserOrg {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ORG.ORG_ID
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  private String orgId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ORG.USER_ID
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  private String userId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column SYS_USER_ORG.LAST_VER
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  private String lastVer;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ORG.LAST_VER
   *
   * @return the value of SYS_USER_ORG.LAST_VER
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  public String getLastVer() {
    return lastVer;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ORG.LAST_VER
   *
   * @param lastVer the value for SYS_USER_ORG.LAST_VER
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  public void setLastVer(String lastVer) {
    this.lastVer = lastVer;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ORG.ORG_ID
   *
   * @return the value of SYS_USER_ORG.ORG_ID
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  public String getOrgId() {
    return orgId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ORG.ORG_ID
   *
   * @param orgId the value for SYS_USER_ORG.ORG_ID
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column SYS_USER_ORG.USER_ID
   *
   * @return the value of SYS_USER_ORG.USER_ID
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column SYS_USER_ORG.USER_ID
   *
   * @param userId the value for SYS_USER_ORG.USER_ID
   *
   * @abatorgenerated Tue May 08 07:05:38 GMT 2012
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }
}