package com.ufgov.zc.common.console.model;

import java.math.BigDecimal;

public class SysUsermanage {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.USER_ID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.USER_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String userCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.USER_NAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String userName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.PASSWORD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.ORG_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String orgType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.ORG_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String orgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.LEVEL_NUM
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short levelNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.IS_LEAF
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short isLeaf;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.GENDER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short gender;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.TELEPHONE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String telephone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.MOBILE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.ENABLED
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short enabled;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.HEADSHIP_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String headshipCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.BIRTHDAY
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String birthday;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.ADDRESS
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.EMAIL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.USER_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short userType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.IS_AUDIT
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short isAudit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.AUDIT_DATE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String auditDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.AUDIT_USER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String auditUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.NICKNAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String nickname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.LAST_VER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String lastVer;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.MB_ID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String mbId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.BELONG_ORG
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String belongOrg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.BELONG_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String belongType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.SECURITY_LEVEL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short securityLevel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.INIT_PASSWORD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private Short initPassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.TITLE_TECH
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String titleTech;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.IDENTITY_CARD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String identityCard;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.RTXUIN
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String rtxuin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.PHOTO
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String photo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.PHOTO_BLOBID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String photoBlobid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.CA_SERIAL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String caSerial;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.CO_NAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String coName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.EMP_INDEX
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private BigDecimal empIndex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column SYS_USERMANAGE.GP_ORG
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    private String gpOrg;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.USER_ID
     *
     * @return the value of SYS_USERMANAGE.USER_ID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.USER_ID
     *
     * @param userId the value for SYS_USERMANAGE.USER_ID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.USER_CODE
     *
     * @return the value of SYS_USERMANAGE.USER_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.USER_CODE
     *
     * @param userCode the value for SYS_USERMANAGE.USER_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.USER_NAME
     *
     * @return the value of SYS_USERMANAGE.USER_NAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.USER_NAME
     *
     * @param userName the value for SYS_USERMANAGE.USER_NAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.PASSWORD
     *
     * @return the value of SYS_USERMANAGE.PASSWORD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.PASSWORD
     *
     * @param password the value for SYS_USERMANAGE.PASSWORD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.ORG_TYPE
     *
     * @return the value of SYS_USERMANAGE.ORG_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.ORG_TYPE
     *
     * @param orgType the value for SYS_USERMANAGE.ORG_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.ORG_CODE
     *
     * @return the value of SYS_USERMANAGE.ORG_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.ORG_CODE
     *
     * @param orgCode the value for SYS_USERMANAGE.ORG_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.LEVEL_NUM
     *
     * @return the value of SYS_USERMANAGE.LEVEL_NUM
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getLevelNum() {
        return levelNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.LEVEL_NUM
     *
     * @param levelNum the value for SYS_USERMANAGE.LEVEL_NUM
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setLevelNum(Short levelNum) {
        this.levelNum = levelNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.IS_LEAF
     *
     * @return the value of SYS_USERMANAGE.IS_LEAF
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.IS_LEAF
     *
     * @param isLeaf the value for SYS_USERMANAGE.IS_LEAF
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setIsLeaf(Short isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.GENDER
     *
     * @return the value of SYS_USERMANAGE.GENDER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.GENDER
     *
     * @param gender the value for SYS_USERMANAGE.GENDER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.TELEPHONE
     *
     * @return the value of SYS_USERMANAGE.TELEPHONE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.TELEPHONE
     *
     * @param telephone the value for SYS_USERMANAGE.TELEPHONE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.MOBILE
     *
     * @return the value of SYS_USERMANAGE.MOBILE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.MOBILE
     *
     * @param mobile the value for SYS_USERMANAGE.MOBILE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.ENABLED
     *
     * @return the value of SYS_USERMANAGE.ENABLED
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.ENABLED
     *
     * @param enabled the value for SYS_USERMANAGE.ENABLED
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setEnabled(Short enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.HEADSHIP_CODE
     *
     * @return the value of SYS_USERMANAGE.HEADSHIP_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getHeadshipCode() {
        return headshipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.HEADSHIP_CODE
     *
     * @param headshipCode the value for SYS_USERMANAGE.HEADSHIP_CODE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setHeadshipCode(String headshipCode) {
        this.headshipCode = headshipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.BIRTHDAY
     *
     * @return the value of SYS_USERMANAGE.BIRTHDAY
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.BIRTHDAY
     *
     * @param birthday the value for SYS_USERMANAGE.BIRTHDAY
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.ADDRESS
     *
     * @return the value of SYS_USERMANAGE.ADDRESS
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.ADDRESS
     *
     * @param address the value for SYS_USERMANAGE.ADDRESS
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.EMAIL
     *
     * @return the value of SYS_USERMANAGE.EMAIL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.EMAIL
     *
     * @param email the value for SYS_USERMANAGE.EMAIL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.USER_TYPE
     *
     * @return the value of SYS_USERMANAGE.USER_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getUserType() {
        return userType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.USER_TYPE
     *
     * @param userType the value for SYS_USERMANAGE.USER_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setUserType(Short userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.IS_AUDIT
     *
     * @return the value of SYS_USERMANAGE.IS_AUDIT
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.IS_AUDIT
     *
     * @param isAudit the value for SYS_USERMANAGE.IS_AUDIT
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setIsAudit(Short isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.AUDIT_DATE
     *
     * @return the value of SYS_USERMANAGE.AUDIT_DATE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.AUDIT_DATE
     *
     * @param auditDate the value for SYS_USERMANAGE.AUDIT_DATE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setAuditDate(String auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.AUDIT_USER
     *
     * @return the value of SYS_USERMANAGE.AUDIT_USER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.AUDIT_USER
     *
     * @param auditUser the value for SYS_USERMANAGE.AUDIT_USER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.NICKNAME
     *
     * @return the value of SYS_USERMANAGE.NICKNAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.NICKNAME
     *
     * @param nickname the value for SYS_USERMANAGE.NICKNAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.LAST_VER
     *
     * @return the value of SYS_USERMANAGE.LAST_VER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getLastVer() {
        return lastVer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.LAST_VER
     *
     * @param lastVer the value for SYS_USERMANAGE.LAST_VER
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setLastVer(String lastVer) {
        this.lastVer = lastVer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.MB_ID
     *
     * @return the value of SYS_USERMANAGE.MB_ID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getMbId() {
        return mbId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.MB_ID
     *
     * @param mbId the value for SYS_USERMANAGE.MB_ID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setMbId(String mbId) {
        this.mbId = mbId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.BELONG_ORG
     *
     * @return the value of SYS_USERMANAGE.BELONG_ORG
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getBelongOrg() {
        return belongOrg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.BELONG_ORG
     *
     * @param belongOrg the value for SYS_USERMANAGE.BELONG_ORG
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setBelongOrg(String belongOrg) {
        this.belongOrg = belongOrg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.BELONG_TYPE
     *
     * @return the value of SYS_USERMANAGE.BELONG_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.BELONG_TYPE
     *
     * @param belongType the value for SYS_USERMANAGE.BELONG_TYPE
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setBelongType(String belongType) {
        this.belongType = belongType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.SECURITY_LEVEL
     *
     * @return the value of SYS_USERMANAGE.SECURITY_LEVEL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getSecurityLevel() {
        return securityLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.SECURITY_LEVEL
     *
     * @param securityLevel the value for SYS_USERMANAGE.SECURITY_LEVEL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setSecurityLevel(Short securityLevel) {
        this.securityLevel = securityLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.INIT_PASSWORD
     *
     * @return the value of SYS_USERMANAGE.INIT_PASSWORD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public Short getInitPassword() {
        return initPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.INIT_PASSWORD
     *
     * @param initPassword the value for SYS_USERMANAGE.INIT_PASSWORD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setInitPassword(Short initPassword) {
        this.initPassword = initPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.TITLE_TECH
     *
     * @return the value of SYS_USERMANAGE.TITLE_TECH
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getTitleTech() {
        return titleTech;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.TITLE_TECH
     *
     * @param titleTech the value for SYS_USERMANAGE.TITLE_TECH
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setTitleTech(String titleTech) {
        this.titleTech = titleTech;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.IDENTITY_CARD
     *
     * @return the value of SYS_USERMANAGE.IDENTITY_CARD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.IDENTITY_CARD
     *
     * @param identityCard the value for SYS_USERMANAGE.IDENTITY_CARD
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.RTXUIN
     *
     * @return the value of SYS_USERMANAGE.RTXUIN
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getRtxuin() {
        return rtxuin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.RTXUIN
     *
     * @param rtxuin the value for SYS_USERMANAGE.RTXUIN
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setRtxuin(String rtxuin) {
        this.rtxuin = rtxuin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.PHOTO
     *
     * @return the value of SYS_USERMANAGE.PHOTO
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.PHOTO
     *
     * @param photo the value for SYS_USERMANAGE.PHOTO
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.PHOTO_BLOBID
     *
     * @return the value of SYS_USERMANAGE.PHOTO_BLOBID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getPhotoBlobid() {
        return photoBlobid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.PHOTO_BLOBID
     *
     * @param photoBlobid the value for SYS_USERMANAGE.PHOTO_BLOBID
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setPhotoBlobid(String photoBlobid) {
        this.photoBlobid = photoBlobid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.CA_SERIAL
     *
     * @return the value of SYS_USERMANAGE.CA_SERIAL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getCaSerial() {
        return caSerial;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.CA_SERIAL
     *
     * @param caSerial the value for SYS_USERMANAGE.CA_SERIAL
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setCaSerial(String caSerial) {
        this.caSerial = caSerial;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.CO_NAME
     *
     * @return the value of SYS_USERMANAGE.CO_NAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getCoName() {
        return coName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.CO_NAME
     *
     * @param coName the value for SYS_USERMANAGE.CO_NAME
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setCoName(String coName) {
        this.coName = coName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.EMP_INDEX
     *
     * @return the value of SYS_USERMANAGE.EMP_INDEX
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public BigDecimal getEmpIndex() {
        return empIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.EMP_INDEX
     *
     * @param empIndex the value for SYS_USERMANAGE.EMP_INDEX
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setEmpIndex(BigDecimal empIndex) {
        this.empIndex = empIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column SYS_USERMANAGE.GP_ORG
     *
     * @return the value of SYS_USERMANAGE.GP_ORG
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public String getGpOrg() {
        return gpOrg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column SYS_USERMANAGE.GP_ORG
     *
     * @param gpOrg the value for SYS_USERMANAGE.GP_ORG
     *
     * @abatorgenerated Tue May 08 06:59:49 GMT 2012
     */
    public void setGpOrg(String gpOrg) {
        this.gpOrg = gpOrg;
    }
}