package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfChargeStandard;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfChargeStandardMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE_STANDARD
	 * @mbggenerated  Tue Jan 13 22:39:22 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal chargeStandardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE_STANDARD
	 * @mbggenerated  Tue Jan 13 22:39:22 CST 2015
	 */
	int insert(SfChargeStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE_STANDARD
	 * @mbggenerated  Tue Jan 13 22:39:22 CST 2015
	 */
	int insertSelective(SfChargeStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE_STANDARD
	 * @mbggenerated  Tue Jan 13 22:39:22 CST 2015
	 */
	SfChargeStandard selectByPrimaryKey(BigDecimal chargeStandardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE_STANDARD
	 * @mbggenerated  Tue Jan 13 22:39:22 CST 2015
	 */
	int updateByPrimaryKeySelective(SfChargeStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE_STANDARD
	 * @mbggenerated  Tue Jan 13 22:39:22 CST 2015
	 */
	int updateByPrimaryKey(SfChargeStandard record);
	
	List getMainDataLst(ElementConditionDto dto);
}