package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfJdResult;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

import java.math.BigDecimal;
import java.util.List;

public interface SfJdResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_RESULT
	 * @mbggenerated  Tue Jan 20 21:10:38 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal jdResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_RESULT
	 * @mbggenerated  Tue Jan 20 21:10:38 CST 2015
	 */
	int insert(SfJdResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_RESULT
	 * @mbggenerated  Tue Jan 20 21:10:38 CST 2015
	 */
	int insertSelective(SfJdResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_RESULT
	 * @mbggenerated  Tue Jan 20 21:10:38 CST 2015
	 */
	SfJdResult selectByPrimaryKey(BigDecimal jdResultId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_RESULT
	 * @mbggenerated  Tue Jan 20 21:10:38 CST 2015
	 */
	int updateByPrimaryKeySelective(SfJdResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_RESULT
	 * @mbggenerated  Tue Jan 20 21:10:38 CST 2015
	 */
	int updateByPrimaryKey(SfJdResult record);
  
  List getMainDataLst(ElementConditionDto elementConditionDto);
}