package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfJdPersonMajor;

public interface SfJdPersonMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_PERSON_MAJOR
     *
     * @mbggenerated Wed Jan 21 20:04:17 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal jdPersonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_PERSON_MAJOR
     *
     * @mbggenerated Wed Jan 21 20:04:17 CST 2015
     */
    int insert(SfJdPersonMajor record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_PERSON_MAJOR
     *
     * @mbggenerated Wed Jan 21 20:04:17 CST 2015
     */
    List selectByPrimaryKey(BigDecimal jdPersonId);

}