package com.ufgov.zc.server.sf.dao;

import java.util.List;

import com.ufgov.zc.common.sf.model.SfMajor;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfMajorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MAJOR
	 * @mbggenerated  Thu Jan 01 01:16:29 CST 2015
	 */
	int deleteByPrimaryKey(String majorCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MAJOR
	 * @mbggenerated  Thu Jan 01 01:16:29 CST 2015
	 */
	int insert(SfMajor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MAJOR
	 * @mbggenerated  Thu Jan 01 01:16:29 CST 2015
	 */
	int insertSelective(SfMajor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MAJOR
	 * @mbggenerated  Thu Jan 01 01:16:29 CST 2015
	 */
	SfMajor selectByPrimaryKey(String majorCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MAJOR
	 * @mbggenerated  Thu Jan 01 01:16:29 CST 2015
	 */
	int updateByPrimaryKeySelective(SfMajor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MAJOR
	 * @mbggenerated  Thu Jan 01 01:16:29 CST 2015
	 */
	int updateByPrimaryKey(SfMajor record);

  List getMajorLst(ElementConditionDto elementConditionDto);

  boolean isUsing(String majorCode);
}