package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfMaterials;

public interface SfMaterialsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MATERIALS
	 * @mbggenerated  Sun Jan 11 06:13:48 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal materialId);
	int deleteByEntrustId(BigDecimal entrustId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MATERIALS
	 * @mbggenerated  Sun Jan 11 06:13:48 CST 2015
	 */
	int insert(SfMaterials record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MATERIALS
	 * @mbggenerated  Sun Jan 11 06:13:48 CST 2015
	 */
	int insertSelective(SfMaterials record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MATERIALS
	 * @mbggenerated  Sun Jan 11 06:13:48 CST 2015
	 */
	SfMaterials selectByPrimaryKey(BigDecimal materialId);
	List selectByEntrustId(BigDecimal entrustId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MATERIALS
	 * @mbggenerated  Sun Jan 11 06:13:48 CST 2015
	 */
	int updateByPrimaryKeySelective(SfMaterials record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_MATERIALS
	 * @mbggenerated  Sun Jan 11 06:13:48 CST 2015
	 */
	int updateByPrimaryKey(SfMaterials record);
}