package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfOutInfoValidateDetail;

public interface SfOutInfoValidateDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_VALIDATE_DETAIL
	 * @mbggenerated  Sat Jan 17 19:38:21 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal outInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_VALIDATE_DETAIL
	 * @mbggenerated  Sat Jan 17 19:38:21 CST 2015
	 */
	int insert(SfOutInfoValidateDetail record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_VALIDATE_DETAIL
	 * @mbggenerated  Sat Jan 17 19:38:21 CST 2015
	 */
	List selectByPrimaryKey(BigDecimal outInfoId);

}