package com.ufgov.zc.common.zc.model;

import java.util.List;

public class ZcHtPrePayBill extends ZcBaseBill {

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column ZC_HT_PRE_PAY_BILL.BILL_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  private String billCode;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column ZC_HT_PRE_PAY_BILL.ZC_MAKE_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  private String zcMakeCode;

  private String zcMakeName;

  private String zcHtName;
  //附件
  private String zcImpFile;
  private String zcImpFileBlobid;

  public String getZcImpFile() {
	return zcImpFile;
  }

  public void setZcImpFile(String zcImpFile) {
	this.zcImpFile = zcImpFile;
  }

  public String getZcImpFileBlobid() {
	return zcImpFileBlobid;
  }

  public void setZcImpFileBlobid(String zcImpFileBlobid) {
	this.zcImpFileBlobid = zcImpFileBlobid;
  }

  /**
   * @return the zcMakeName
   */
  public String getZcMakeName() {
    return zcMakeName;
  }

  /**
   * @param zcMakeName the zcMakeName to set
   */
  public void setZcMakeName(String zcMakeName) {
    this.zcMakeName = zcMakeName;
  }

  /**
   * @return the zcHtName
   */
  public String getZcHtName() {
    return zcHtName;
  }

  /**
   * @param zcHtName the zcHtName to set
   */
  public void setZcHtName(String zcHtName) {
    this.zcHtName = zcHtName;
  }

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column ZC_HT_PRE_PAY_BILL.ZC_HT_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  private String zcHtCode;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column ZC_HT_PRE_PAY_BILL.REMARK
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  private String remark;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column ZC_HT_PRE_PAY_BILL.STATUS
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  private String status;

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column ZC_HT_PRE_PAY_BILL.BILL_CODE
   * @return  the value of ZC_HT_PRE_PAY_BILL.BILL_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public String getBillCode() {
    return billCode;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column ZC_HT_PRE_PAY_BILL.BILL_CODE
   * @param billCode  the value for ZC_HT_PRE_PAY_BILL.BILL_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public void setBillCode(String billCode) {
    this.billCode = billCode;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column ZC_HT_PRE_PAY_BILL.ZC_MAKE_CODE
   * @return  the value of ZC_HT_PRE_PAY_BILL.ZC_MAKE_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public String getZcMakeCode() {
    return zcMakeCode;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column ZC_HT_PRE_PAY_BILL.ZC_MAKE_CODE
   * @param zcMakeCode  the value for ZC_HT_PRE_PAY_BILL.ZC_MAKE_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public void setZcMakeCode(String zcMakeCode) {
    this.zcMakeCode = zcMakeCode;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column ZC_HT_PRE_PAY_BILL.ZC_HT_CODE
   * @return  the value of ZC_HT_PRE_PAY_BILL.ZC_HT_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public String getZcHtCode() {
    return zcHtCode;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column ZC_HT_PRE_PAY_BILL.ZC_HT_CODE
   * @param zcHtCode  the value for ZC_HT_PRE_PAY_BILL.ZC_HT_CODE
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public void setZcHtCode(String zcHtCode) {
    this.zcHtCode = zcHtCode;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column ZC_HT_PRE_PAY_BILL.REMARK
   * @return  the value of ZC_HT_PRE_PAY_BILL.REMARK
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column ZC_HT_PRE_PAY_BILL.REMARK
   * @param remark  the value for ZC_HT_PRE_PAY_BILL.REMARK
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column ZC_HT_PRE_PAY_BILL.STATUS
   * @return  the value of ZC_HT_PRE_PAY_BILL.STATUS
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column ZC_HT_PRE_PAY_BILL.STATUS
   * @param status  the value for ZC_HT_PRE_PAY_BILL.STATUS
   * @abatorgenerated  Wed Aug 08 08:00:48 GMT 2012
   */
  public void setStatus(String status) {
    this.status = status;
  }

  private ZcPProMake zcPProMake;

  private ZcXmcgHt zcXmcgHt;

  private List BillList;

  /**
   * @return the zcPProMake
   */
  public ZcPProMake getZcPProMake() {
    return zcPProMake;
  }

  /**
   * @param zcPProMake the zcPProMake to set
   */
  public void setZcPProMake(ZcPProMake zcPProMake) {
    this.zcPProMake = zcPProMake;
  }

  /**
   * @return the zcXmcgHt
   */
  public ZcXmcgHt getZcXmcgHt() {
    return zcXmcgHt;
  }

  /**
   * @param zcXmcgHt the zcXmcgHt to set
   */
  public void setZcXmcgHt(ZcXmcgHt zcXmcgHt) {
    this.zcXmcgHt = zcXmcgHt;
  }

  /**
   * @return the billList
   */
  public List getBillList() {
    return BillList;
  }

  /**
   * @param billList the billList to set
   */
  public void setBillList(List billList) {
    BillList = billList;
  }

}