package com.ufgov.zc.common.zc.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ZcPProReturnBi implements Serializable {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_RETURN_BI.ZC_BAL_ID
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  private String zcBalId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_RETURN_BI.ZC_BI_NO
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  private String zcBiNo;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_RETURN_BI.ZC_BI_BAL
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  private BigDecimal zcBiBal;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_RETURN_BI.SEND_DOC_NAME
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  private String sendDocName;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_RETURN_BI.ZC_BAL_ID
   *
   * @return the value of ZC_P_PRO_RETURN_BI.ZC_BAL_ID
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public String getZcBalId() {
    return zcBalId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_RETURN_BI.ZC_BAL_ID
   *
   * @param zcBalId the value for ZC_P_PRO_RETURN_BI.ZC_BAL_ID
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public void setZcBalId(String zcBalId) {
    this.zcBalId = zcBalId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_RETURN_BI.ZC_BI_NO
   *
   * @return the value of ZC_P_PRO_RETURN_BI.ZC_BI_NO
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public String getZcBiNo() {
    return zcBiNo;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_RETURN_BI.ZC_BI_NO
   *
   * @param zcBiNo the value for ZC_P_PRO_RETURN_BI.ZC_BI_NO
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public void setZcBiNo(String zcBiNo) {
    this.zcBiNo = zcBiNo;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_RETURN_BI.ZC_BI_BAL
   *
   * @return the value of ZC_P_PRO_RETURN_BI.ZC_BI_BAL
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public BigDecimal getZcBiBal() {
    return zcBiBal;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_RETURN_BI.ZC_BI_BAL
   *
   * @param zcBiBal the value for ZC_P_PRO_RETURN_BI.ZC_BI_BAL
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public void setZcBiBal(BigDecimal zcBiBal) {
    this.zcBiBal = zcBiBal;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_RETURN_BI.SEND_DOC_NAME
   *
   * @return the value of ZC_P_PRO_RETURN_BI.SEND_DOC_NAME
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public String getSendDocName() {
    return sendDocName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_RETURN_BI.SEND_DOC_NAME
   *
   * @param sendDocName the value for ZC_P_PRO_RETURN_BI.SEND_DOC_NAME
   *
   * @abatorgenerated Sat Aug 18 13:40:38 GMT 2012
   */
  public void setSendDocName(String sendDocName) {
    this.sendDocName = sendDocName;
  }

  private String tempId;

  /**
   * @return the tempId
   */
  public String getTempId() {
    return tempId;
  }

  /**
   * @param tempId the tempId to set
   */
  public void setTempId(String tempId) {
    this.tempId = tempId;
  }

  private String zcAmBillNo;

  /**
   * @return the zcAmBillNo
   */
  public String getZcAmBillNo() {
    return zcAmBillNo;
  }

  /**
   * @param zcAmBillNo the zcAmBillNo to set
   */
  public void setZcAmBillNo(String zcAmBillNo) {
    this.zcAmBillNo = zcAmBillNo;
  }

  /**
   * @return the zcPaytypeCode
   */
  public String getZcPaytypeCode() {
    return zcPaytypeCode;
  }

  /**
   * @param zcPaytypeCode the zcPaytypeCode to set
   */
  public void setZcPaytypeCode(String zcPaytypeCode) {
    this.zcPaytypeCode = zcPaytypeCode;
  }

  private String zcPaytypeCode;
}