package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfCharge;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfChargeMapper  {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE
	 * @mbggenerated  Wed Jan 14 01:24:40 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal chargeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE
	 * @mbggenerated  Wed Jan 14 01:24:40 CST 2015
	 */
	int insert(SfCharge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE
	 * @mbggenerated  Wed Jan 14 01:24:40 CST 2015
	 */
	int insertSelective(SfCharge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE
	 * @mbggenerated  Wed Jan 14 01:24:40 CST 2015
	 */
	SfCharge selectByPrimaryKey(BigDecimal chargeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE
	 * @mbggenerated  Wed Jan 14 01:24:40 CST 2015
	 */
	int updateByPrimaryKeySelective(SfCharge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_CHARGE
	 * @mbggenerated  Wed Jan 14 01:24:40 CST 2015
	 */
	int updateByPrimaryKey(SfCharge record);
	
	List getMainDataLst(ElementConditionDto elementConditionDto);
}