package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfDossier;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

import java.math.BigDecimal;
import java.util.List;

public interface SfDossierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_DOSSIER
     *
     * @mbggenerated Fri Jan 23 00:45:31 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal dossierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_DOSSIER
     *
     * @mbggenerated Fri Jan 23 00:45:31 CST 2015
     */
    int insert(SfDossier record);

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_DOSSIER
     *
     * @mbggenerated Fri Jan 23 00:45:31 CST 2015
     */
    SfDossier selectByPrimaryKey(BigDecimal dossierId);
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_DOSSIER
     *
     * @mbggenerated Fri Jan 23 00:45:31 CST 2015
     */
    int updateByPrimaryKey(SfDossier record);
    
    List getMainDataLst(ElementConditionDto elementConditionDto);
}