package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfEvaluationPerson;

public interface SfEvaluationPersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_EVALUATION_PERSON
	 * @mbggenerated  Mon Jan 12 18:41:02 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal evaluationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_EVALUATION_PERSON
	 * @mbggenerated  Mon Jan 12 18:41:02 CST 2015
	 */
	int insert(SfEvaluationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_EVALUATION_PERSON
	 * @mbggenerated  Mon Jan 12 18:41:02 CST 2015
	 */
	int insertSelective(SfEvaluationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_EVALUATION_PERSON
	 * @mbggenerated  Mon Jan 12 18:41:02 CST 2015
	 */
	List selectByPrimaryKey(BigDecimal evaluationId);

}