package com.ufgov.zc.server.sf.dao;

import java.util.List;

import com.ufgov.zc.common.sf.model.SfJdDocType;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfJdDocTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_DOC_TYPE
     *
     * @mbggenerated Thu Jan 22 00:09:07 CST 2015
     */
    int deleteByPrimaryKey(String docTypeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_DOC_TYPE
     *
     * @mbggenerated Thu Jan 22 00:09:07 CST 2015
     */
    int insert(SfJdDocType record);
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_DOC_TYPE
     *
     * @mbggenerated Thu Jan 22 00:09:07 CST 2015
     */
    SfJdDocType selectByPrimaryKey(String docTypeCode);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_DOC_TYPE
     *
     * @mbggenerated Thu Jan 22 00:09:07 CST 2015
     */
    int updateByPrimaryKey(SfJdDocType record);
    
    List getMainDataLst(ElementConditionDto dto);
}