package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfOutInfoDetail;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfOutInfoDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_DETAIL
	 * @mbggenerated  Sat Jan 17 19:24:26 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal outInfoDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_DETAIL
	 * @mbggenerated  Sat Jan 17 19:24:26 CST 2015
	 */
	int insert(SfOutInfoDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_DETAIL
	 * @mbggenerated  Sat Jan 17 19:24:26 CST 2015
	 */
	SfOutInfoDetail selectByPrimaryKey(BigDecimal outInfoDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_OUT_INFO_DETAIL
	 * @mbggenerated  Sat Jan 17 19:24:26 CST 2015
	 */
	int updateByPrimaryKey(SfOutInfoDetail record);
	
	List selectByOutInfoId(ElementConditionDto dto);
	
  int deleteByOutInfoId(BigDecimal outInfoId);
}