package com.ufgov.zc.server.sf.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.sf.model.SfReceipt;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfReceiptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_RECEIPT
	 * @mbggenerated  Fri Jan 16 03:07:34 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal receiptId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_RECEIPT
	 * @mbggenerated  Fri Jan 16 03:07:34 CST 2015
	 */
	int insert(SfReceipt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_RECEIPT
	 * @mbggenerated  Fri Jan 16 03:07:34 CST 2015
	 */
	int insertSelective(SfReceipt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_RECEIPT
	 * @mbggenerated  Fri Jan 16 03:07:34 CST 2015
	 */
	SfReceipt selectByPrimaryKey(BigDecimal receiptId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_RECEIPT
	 * @mbggenerated  Fri Jan 16 03:07:34 CST 2015
	 */
	int updateByPrimaryKeySelective(SfReceipt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_RECEIPT
	 * @mbggenerated  Fri Jan 16 03:07:34 CST 2015
	 */
	int updateByPrimaryKey(SfReceipt record);
  
  List getMainDataLst(ElementConditionDto elementConditionDto);
}