package com.ufgov.zc.common.zc.model;

import java.util.Date;

public class ZcEbRequirementConfirm extends ZcBaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.REQ_CODE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String packCode;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.SN
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String sn;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.DESCRIPTION
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String description;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_NAME
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String expertName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_DUTY
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String expertDuty;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_WEITUO_BLOBID
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String expertWeituoBlobid;

  private String expertWeituoName;

  /**
   * @return the expertWeituoName
   */
  public String getExpertWeituoName() {
    return expertWeituoName;
  }

  /**
   * @param expertWeituoName the expertWeituoName to set
   */
  public void setExpertWeituoName(String expertWeituoName) {
    this.expertWeituoName = expertWeituoName;
  }

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String providerQu;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU_BLOBID
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String providerQuBlobid;

  private String providerQuName;

  /**
   * @return the providerQuName
   */
  public String getProviderQuName() {
    return providerQuName;
  }

  /**
   * @param providerQuName the providerQuName to set
   */
  public void setProviderQuName(String providerQuName) {
    this.providerQuName = providerQuName;
  }

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private Date deliveryDate;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_ADDRESS
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String deliveryAddress;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.IS_MARGIN
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String isMargin;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.GUARANTEE_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String guaranteeDate;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_PAY_TYPE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String marginPayType;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private Date marginReturnDate;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_COND
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String marginReturnCond;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.AFTER_SALES_SER
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String afterSalesSer;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.FORMULA_TYPE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String formulaType;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.IS_OVER_BUDGET
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String isOverBudget;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.IS_QA
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String isQa;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQUIREMENT_CONFIRM.REMARK
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  private String remark;

  /**
   * @return the packCode
   */
  public String getPackCode() {
    return packCode;
  }

  /**
   * @param packCode the packCode to set
   */
  public void setPackCode(String packCode) {
    this.packCode = packCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.SN
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.SN
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getSn() {
    return sn;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.SN
   *
   * @param sn the value for ZC_EB_REQUIREMENT_CONFIRM.SN
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setSn(String sn) {
    this.sn = sn;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.DESCRIPTION
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.DESCRIPTION
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getDescription() {
    return description;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.DESCRIPTION
   *
   * @param description the value for ZC_EB_REQUIREMENT_CONFIRM.DESCRIPTION
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_NAME
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.EXPERT_NAME
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getExpertName() {
    return expertName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_NAME
   *
   * @param expertName the value for ZC_EB_REQUIREMENT_CONFIRM.EXPERT_NAME
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setExpertName(String expertName) {
    this.expertName = expertName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_DUTY
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.EXPERT_DUTY
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getExpertDuty() {
    return expertDuty;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_DUTY
   *
   * @param expertDuty the value for ZC_EB_REQUIREMENT_CONFIRM.EXPERT_DUTY
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setExpertDuty(String expertDuty) {
    this.expertDuty = expertDuty;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_WEITUO_BLOBID
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.EXPERT_WEITUO_BLOBID
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getExpertWeituoBlobid() {
    return expertWeituoBlobid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.EXPERT_WEITUO_BLOBID
   *
   * @param expertWeituoBlobid the value for ZC_EB_REQUIREMENT_CONFIRM.EXPERT_WEITUO_BLOBID
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setExpertWeituoBlobid(String expertWeituoBlobid) {
    this.expertWeituoBlobid = expertWeituoBlobid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getProviderQu() {
    return providerQu;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU
   *
   * @param providerQu the value for ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setProviderQu(String providerQu) {
    this.providerQu = providerQu;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU_BLOBID
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU_BLOBID
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getProviderQuBlobid() {
    return providerQuBlobid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU_BLOBID
   *
   * @param providerQuBlobid the value for ZC_EB_REQUIREMENT_CONFIRM.PROVIDER_QU_BLOBID
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setProviderQuBlobid(String providerQuBlobid) {
    this.providerQuBlobid = providerQuBlobid;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_DATE
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public Date getDeliveryDate() {
    return deliveryDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_DATE
   *
   * @param deliveryDate the value for ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setDeliveryDate(Date deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_ADDRESS
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_ADDRESS
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getDeliveryAddress() {
    return deliveryAddress;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_ADDRESS
   *
   * @param deliveryAddress the value for ZC_EB_REQUIREMENT_CONFIRM.DELIVERY_ADDRESS
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setDeliveryAddress(String deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.IS_MARGIN
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.IS_MARGIN
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getIsMargin() {
    return isMargin;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.IS_MARGIN
   *
   * @param isMargin the value for ZC_EB_REQUIREMENT_CONFIRM.IS_MARGIN
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setIsMargin(String isMargin) {
    this.isMargin = isMargin;
  }

  /**
   * @return the guaranteeDate
   */
  public String getGuaranteeDate() {
    return guaranteeDate;
  }

  /**
   * @param guaranteeDate the guaranteeDate to set
   */
  public void setGuaranteeDate(String guaranteeDate) {
    this.guaranteeDate = guaranteeDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_PAY_TYPE
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.MARGIN_PAY_TYPE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getMarginPayType() {
    return marginPayType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_PAY_TYPE
   *
   * @param marginPayType the value for ZC_EB_REQUIREMENT_CONFIRM.MARGIN_PAY_TYPE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setMarginPayType(String marginPayType) {
    this.marginPayType = marginPayType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_DATE
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public Date getMarginReturnDate() {
    return marginReturnDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_DATE
   *
   * @param marginReturnDate the value for ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_DATE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setMarginReturnDate(Date marginReturnDate) {
    this.marginReturnDate = marginReturnDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_COND
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_COND
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getMarginReturnCond() {
    return marginReturnCond;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_COND
   *
   * @param marginReturnCond the value for ZC_EB_REQUIREMENT_CONFIRM.MARGIN_RETURN_COND
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setMarginReturnCond(String marginReturnCond) {
    this.marginReturnCond = marginReturnCond;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.AFTER_SALES_SER
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.AFTER_SALES_SER
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getAfterSalesSer() {
    return afterSalesSer;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.AFTER_SALES_SER
   *
   * @param afterSalesSer the value for ZC_EB_REQUIREMENT_CONFIRM.AFTER_SALES_SER
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setAfterSalesSer(String afterSalesSer) {
    this.afterSalesSer = afterSalesSer;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.FORMULA_TYPE
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.FORMULA_TYPE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getFormulaType() {
    return formulaType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.FORMULA_TYPE
   *
   * @param formulaType the value for ZC_EB_REQUIREMENT_CONFIRM.FORMULA_TYPE
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setFormulaType(String formulaType) {
    this.formulaType = formulaType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.IS_OVER_BUDGET
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.IS_OVER_BUDGET
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getIsOverBudget() {
    return isOverBudget;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.IS_OVER_BUDGET
   *
   * @param isOverBudget the value for ZC_EB_REQUIREMENT_CONFIRM.IS_OVER_BUDGET
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setIsOverBudget(String isOverBudget) {
    this.isOverBudget = isOverBudget;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.IS_QA
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.IS_QA
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getIsQa() {
    return isQa;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.IS_QA
   *
   * @param isQa the value for ZC_EB_REQUIREMENT_CONFIRM.IS_QA
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setIsQa(String isQa) {
    this.isQa = isQa;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQUIREMENT_CONFIRM.REMARK
   *
   * @return the value of ZC_EB_REQUIREMENT_CONFIRM.REMARK
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQUIREMENT_CONFIRM.REMARK
   *
   * @param remark the value for ZC_EB_REQUIREMENT_CONFIRM.REMARK
   *
   * @abatorgenerated Fri Aug 17 07:29:16 GMT 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  private String payCond;

  /**
   * @return the payCond
   */
  public String getPayCond() {
    return payCond;
  }

  /**
   * @param payCond the payCond to set
   */
  public void setPayCond(String payCond) {
    this.payCond = payCond;
  }

  private Date payDate;

  /**
   * @return the payDate
   */
  public Date getPayDate() {
    return payDate;
  }

  /**
   * @param payDate the payDate to set
   */
  public void setPayDate(Date payDate) {
    this.payDate = payDate;
  }

  private String zcBiDesc;

  /**
   * @return the zcBiDesc
   */
  public String getZcBiDesc() {
    return zcBiDesc;
  }

  /**
   * @param zcBiDesc the zcBiDesc to set
   */
  public void setZcBiDesc(String zcBiDesc) {
    this.zcBiDesc = zcBiDesc;
  }

  private String isBidBond;

  private String bondReturnCond;

  /**
   * @return the isBidBond
   */
  public String getIsBidBond() {
    return isBidBond;
  }

  /**
   * @param isBidBond the isBidBond to set
   */
  public void setIsBidBond(String isBidBond) {
    this.isBidBond = isBidBond;
  }

  /**
   * @return the bondReturnCond
   */
  public String getBondReturnCond() {
    return bondReturnCond;
  }

  /**
   * @param bondReturnCond the bondReturnCond to set
   */
  public void setBondReturnCond(String bondReturnCond) {
    this.bondReturnCond = bondReturnCond;
  }

  public boolean isDataChanged = false;

}