package com.ufgov.zc.common.zc.model;

import java.util.Date;

public class ZcEbReqFile extends ZcBaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.REQ_CODE
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String reqCode;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.SN
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String sn;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.CREATOR
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String creator;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.UPLOADER
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String uploader;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.CREATE_TIME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private Date createTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.UPLOAD_TIME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private Date uploadTime;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.REMARK
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String remark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.FILE_NAME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String fileName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_EB_REQ_FILE.STATUS
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  private String status;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.REQ_CODE
   *
   * @return the value of ZC_EB_REQ_FILE.REQ_CODE
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public boolean isDataChaged;

  private byte[] fileContent;

  public String getReqCode() {
    return reqCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.REQ_CODE
   *
   * @param reqCode the value for ZC_EB_REQ_FILE.REQ_CODE
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setReqCode(String reqCode) {
    this.reqCode = reqCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.SN
   *
   * @return the value of ZC_EB_REQ_FILE.SN
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public String getSn() {
    return sn;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.SN
   *
   * @param sn the value for ZC_EB_REQ_FILE.SN
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setSn(String sn) {
    this.sn = sn;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.CREATOR
   *
   * @return the value of ZC_EB_REQ_FILE.CREATOR
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public String getCreator() {
    return creator;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.CREATOR
   *
   * @param creator the value for ZC_EB_REQ_FILE.CREATOR
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setCreator(String creator) {
    this.creator = creator;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.UPLOADER
   *
   * @return the value of ZC_EB_REQ_FILE.UPLOADER
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public String getUploader() {
    return uploader;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.UPLOADER
   *
   * @param uploader the value for ZC_EB_REQ_FILE.UPLOADER
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setUploader(String uploader) {
    this.uploader = uploader;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.CREATE_TIME
   *
   * @return the value of ZC_EB_REQ_FILE.CREATE_TIME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.CREATE_TIME
   *
   * @param createTime the value for ZC_EB_REQ_FILE.CREATE_TIME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.UPLOAD_TIME
   *
   * @return the value of ZC_EB_REQ_FILE.UPLOAD_TIME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public Date getUploadTime() {
    return uploadTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.UPLOAD_TIME
   *
   * @param uploadTime the value for ZC_EB_REQ_FILE.UPLOAD_TIME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setUploadTime(Date uploadTime) {
    this.uploadTime = uploadTime;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.REMARK
   *
   * @return the value of ZC_EB_REQ_FILE.REMARK
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.REMARK
   *
   * @param remark the value for ZC_EB_REQ_FILE.REMARK
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.FILE_NAME
   *
   * @return the value of ZC_EB_REQ_FILE.FILE_NAME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public String getFileName() {
    return fileName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.FILE_NAME
   *
   * @param fileName the value for ZC_EB_REQ_FILE.FILE_NAME
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_EB_REQ_FILE.STATUS
   *
   * @return the value of ZC_EB_REQ_FILE.STATUS
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_EB_REQ_FILE.STATUS
   *
   * @param status the value for ZC_EB_REQ_FILE.STATUS
   *
   * @abatorgenerated Tue Oct 16 07:22:30 GMT 2012
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * @return the isDataChaged
   */
  public boolean isDataChaged() {
    return isDataChaged;
  }

  /**
   * @param isDataChaged the isDataChaged to set
   */
  public void setDataChaged(boolean isDataChaged) {
    this.isDataChaged = isDataChaged;
  }

  /**
   * @return the fileContent
   */
  public byte[] getFileContent() {
    return fileContent;
  }

  /**
   * @param fileContent the fileContent to set
   */
  public void setFileContent(byte[] fileContent) {
    this.fileContent = fileContent;
  }

}