package com.ufgov.zc.common.zc.model;

import java.math.BigDecimal;
import java.util.Date;

public class ZcHtPrePayBillItem extends ZcBaseBill {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_HT_PRE_PAY_BILL_ITEM.BILL_CODE
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  private String billCode;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_HT_PRE_PAY_BILL_ITEM.PAY_ORDER
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  private String payOrder;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_HT_PRE_PAY_BILL_ITEM.PAY_MONEY
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  private BigDecimal payMoney;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_HT_PRE_PAY_BILL_ITEM.REMARK
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  private String remark;


  private String tempId;
  private Date payDate;
  private String payMonth;
  private String payYear;
  private String payQrCode;
  private String status;

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.BILL_CODE
   *
   * @return the value of ZC_HT_PRE_PAY_BILL_ITEM.BILL_CODE
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public String getBillCode() {
    return billCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.BILL_CODE
   *
   * @param billCode the value for ZC_HT_PRE_PAY_BILL_ITEM.BILL_CODE
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public void setBillCode(String billCode) {
    this.billCode = billCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.PAY_ORDER
   *
   * @return the value of ZC_HT_PRE_PAY_BILL_ITEM.PAY_ORDER
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public String getPayOrder() {
    return payOrder;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.PAY_ORDER
   *
   * @param payOrder the value for ZC_HT_PRE_PAY_BILL_ITEM.PAY_ORDER
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public void setPayOrder(String payOrder) {
    this.payOrder = payOrder;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.PAY_MONEY
   *
   * @return the value of ZC_HT_PRE_PAY_BILL_ITEM.PAY_MONEY
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public BigDecimal getPayMoney() {
    return payMoney;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.PAY_MONEY
   *
   * @param payMoney the value for ZC_HT_PRE_PAY_BILL_ITEM.PAY_MONEY
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public void setPayMoney(BigDecimal payMoney) {
    this.payMoney = payMoney;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.REMARK
   *
   * @return the value of ZC_HT_PRE_PAY_BILL_ITEM.REMARK
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_HT_PRE_PAY_BILL_ITEM.REMARK
   *
   * @param remark the value for ZC_HT_PRE_PAY_BILL_ITEM.REMARK
   *
   * @abatorgenerated Wed Aug 08 07:52:10 GMT 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * @return the tempId
   */
  public String getTempId() {
    return tempId;
  }

  /**
   * @param tempId the tempId to set
   */
  public void setTempId(String tempId) {
    this.tempId = tempId;
  }

  private String percent;

  /**
   * @return the percent
   */
  public String getPercent() {
    return percent;
  }

  /**
   * @param percent the percent to set
   */
  public void setPercent(String percent) {
    this.percent = percent;
  }

  public String getPayQrCode() {
    return payQrCode;
  }

  public void setPayQrCode(String payQrCode) {
    this.payQrCode = payQrCode;
  }

  public String getPayMonth() {
	return payMonth;
  }

  public void setPayMonth(String payMonth) {
	this.payMonth = payMonth;
  }

  public String getPayYear() {
	return payYear;
  }

  public void setPayYear(String payYear) {
	this.payYear = payYear;
  }

  /**
   * @return the payDate
   */
  public Date getPayDate() {
    return payDate;
  }

  /**
   * @param payDate the payDate to set
   */
  public void setPayDate(Date payDate) {
    this.payDate = payDate;
  }

}