package com.ufgov.zc.common.zc.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class ZcPProBalChg extends ZcBaseBill implements Serializable {
  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.BAL_CHG_ID
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String balChgId;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_CODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcMakeCode;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_NAME
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcMakeName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_LINKMAN
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcMakeLinkman;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_TEL
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcMakeTel;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.STATUS
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String status;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_CODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcInputCode;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_NAME
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcInputName;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_DATE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private Date zcInputDate;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.REMARK
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String remark;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_MONEY_BI_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private BigDecimal zcMoneyBiSum;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_MONEY_ZC_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private BigDecimal zcMoneyZcSum;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_PIFU_CGFS
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcPifuCgfs;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_PITEM_MODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcPitemMode;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_DIYU_DAIMA
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcDiyuDaima;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_FUKUAN_TYPE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private String zcFukuanType;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_YEP_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private BigDecimal zcYepSum;

  /**
   * This field was generated by Abator for iBATIS.
   * This field corresponds to the database column ZC_P_PRO_BAL_CHG.ZC_BI_NZJZ_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  private BigDecimal zcBiNzjzSum;

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.BAL_CHG_ID
   *
   * @return the value of ZC_P_PRO_BAL_CHG.BAL_CHG_ID
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getBalChgId() {
    return balChgId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.BAL_CHG_ID
   *
   * @param balChgId the value for ZC_P_PRO_BAL_CHG.BAL_CHG_ID
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setBalChgId(String balChgId) {
    this.balChgId = balChgId;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_CODE
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_MAKE_CODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcMakeCode() {
    return zcMakeCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_CODE
   *
   * @param zcMakeCode the value for ZC_P_PRO_BAL_CHG.ZC_MAKE_CODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcMakeCode(String zcMakeCode) {
    this.zcMakeCode = zcMakeCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_NAME
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_MAKE_NAME
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcMakeName() {
    return zcMakeName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_NAME
   *
   * @param zcMakeName the value for ZC_P_PRO_BAL_CHG.ZC_MAKE_NAME
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcMakeName(String zcMakeName) {
    this.zcMakeName = zcMakeName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_LINKMAN
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_MAKE_LINKMAN
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcMakeLinkman() {
    return zcMakeLinkman;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_LINKMAN
   *
   * @param zcMakeLinkman the value for ZC_P_PRO_BAL_CHG.ZC_MAKE_LINKMAN
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcMakeLinkman(String zcMakeLinkman) {
    this.zcMakeLinkman = zcMakeLinkman;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_TEL
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_MAKE_TEL
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcMakeTel() {
    return zcMakeTel;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_MAKE_TEL
   *
   * @param zcMakeTel the value for ZC_P_PRO_BAL_CHG.ZC_MAKE_TEL
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcMakeTel(String zcMakeTel) {
    this.zcMakeTel = zcMakeTel;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.STATUS
   *
   * @return the value of ZC_P_PRO_BAL_CHG.STATUS
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.STATUS
   *
   * @param status the value for ZC_P_PRO_BAL_CHG.STATUS
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_CODE
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_INPUT_CODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcInputCode() {
    return zcInputCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_CODE
   *
   * @param zcInputCode the value for ZC_P_PRO_BAL_CHG.ZC_INPUT_CODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcInputCode(String zcInputCode) {
    this.zcInputCode = zcInputCode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_NAME
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_INPUT_NAME
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcInputName() {
    return zcInputName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_NAME
   *
   * @param zcInputName the value for ZC_P_PRO_BAL_CHG.ZC_INPUT_NAME
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcInputName(String zcInputName) {
    this.zcInputName = zcInputName;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_DATE
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_INPUT_DATE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public Date getZcInputDate() {
    return zcInputDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_INPUT_DATE
   *
   * @param zcInputDate the value for ZC_P_PRO_BAL_CHG.ZC_INPUT_DATE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcInputDate(Date zcInputDate) {
    this.zcInputDate = zcInputDate;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.REMARK
   *
   * @return the value of ZC_P_PRO_BAL_CHG.REMARK
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.REMARK
   *
   * @param remark the value for ZC_P_PRO_BAL_CHG.REMARK
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_MONEY_BI_SUM
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_MONEY_BI_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public BigDecimal getZcMoneyBiSum() {
    return zcMoneyBiSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_MONEY_BI_SUM
   *
   * @param zcMoneyBiSum the value for ZC_P_PRO_BAL_CHG.ZC_MONEY_BI_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcMoneyBiSum(BigDecimal zcMoneyBiSum) {
    this.zcMoneyBiSum = zcMoneyBiSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_MONEY_ZC_SUM
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_MONEY_ZC_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public BigDecimal getZcMoneyZcSum() {
    return zcMoneyZcSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_MONEY_ZC_SUM
   *
   * @param zcMoneyZcSum the value for ZC_P_PRO_BAL_CHG.ZC_MONEY_ZC_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcMoneyZcSum(BigDecimal zcMoneyZcSum) {
    this.zcMoneyZcSum = zcMoneyZcSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_PIFU_CGFS
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_PIFU_CGFS
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcPifuCgfs() {
    return zcPifuCgfs;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_PIFU_CGFS
   *
   * @param zcPifuCgfs the value for ZC_P_PRO_BAL_CHG.ZC_PIFU_CGFS
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcPifuCgfs(String zcPifuCgfs) {
    this.zcPifuCgfs = zcPifuCgfs;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_PITEM_MODE
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_PITEM_MODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcPitemMode() {
    return zcPitemMode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_PITEM_MODE
   *
   * @param zcPitemMode the value for ZC_P_PRO_BAL_CHG.ZC_PITEM_MODE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcPitemMode(String zcPitemMode) {
    this.zcPitemMode = zcPitemMode;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_DIYU_DAIMA
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_DIYU_DAIMA
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcDiyuDaima() {
    return zcDiyuDaima;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_DIYU_DAIMA
   *
   * @param zcDiyuDaima the value for ZC_P_PRO_BAL_CHG.ZC_DIYU_DAIMA
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcDiyuDaima(String zcDiyuDaima) {
    this.zcDiyuDaima = zcDiyuDaima;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_FUKUAN_TYPE
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_FUKUAN_TYPE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public String getZcFukuanType() {
    return zcFukuanType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_FUKUAN_TYPE
   *
   * @param zcFukuanType the value for ZC_P_PRO_BAL_CHG.ZC_FUKUAN_TYPE
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcFukuanType(String zcFukuanType) {
    this.zcFukuanType = zcFukuanType;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_YEP_SUM
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_YEP_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public BigDecimal getZcYepSum() {
    return zcYepSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_YEP_SUM
   *
   * @param zcYepSum the value for ZC_P_PRO_BAL_CHG.ZC_YEP_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcYepSum(BigDecimal zcYepSum) {
    this.zcYepSum = zcYepSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method returns the value of the database column ZC_P_PRO_BAL_CHG.ZC_BI_NZJZ_SUM
   *
   * @return the value of ZC_P_PRO_BAL_CHG.ZC_BI_NZJZ_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public BigDecimal getZcBiNzjzSum() {
    return zcBiNzjzSum;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method sets the value of the database column ZC_P_PRO_BAL_CHG.ZC_BI_NZJZ_SUM
   *
   * @param zcBiNzjzSum the value for ZC_P_PRO_BAL_CHG.ZC_BI_NZJZ_SUM
   *
   * @abatorgenerated Thu Jul 12 07:44:59 GMT 2012
   */
  public void setZcBiNzjzSum(BigDecimal zcBiNzjzSum) {
    this.zcBiNzjzSum = zcBiNzjzSum;
  }

  private List zcPProChgBiList;

  /**
   * @return the zcPProChgBiList
   */
  public List getZcPProChgBiList() {
    return zcPProChgBiList;
  }

  /**
   * @param zcPProChgBiList the zcPProChgBiList to set
   */
  public void setZcPProChgBiList(List zcPProChgBiList) {
    this.zcPProChgBiList = zcPProChgBiList;
  }

  private ZcPProMake zcPProMake;

  /**
   * @return the zcPProMake
   */
  public ZcPProMake getZcPProMake() {
    return zcPProMake;
  }

  /**
   * @param zcPProMake the zcPProMake to set
   */
  public void setZcPProMake(ZcPProMake zcPProMake) {
    this.zcPProMake = zcPProMake;
  }

  private List xmcgHtList;

  /**
   * @return the xmcgHtList
   */
  public List getXmcgHtList() {
    return xmcgHtList;
  }

  /**
   * @param xmcgHtList the xmcgHtList to set
   */
  public void setXmcgHtList(List xmcgHtList) {
    this.xmcgHtList = xmcgHtList;
  }

  private List oldBiList;

  /**
   * @return the oldBiList
   */
  public List getOldBiList() {
    return oldBiList;
  }

  /**
   * @param oldBiList the oldBiList to set
   */
  public void setOldBiList(List oldBiList) {
    this.oldBiList = oldBiList;
  }

}