package com.ufgov.zc.common.commonbiz.model;

import java.util.Date;

public class MaCompany extends MaCompanyKey {

  /**
   * 
   */
  private static final long serialVersionUID = 436921940745243569L;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_TYPE_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coTypeCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.GB_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String gbCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coName;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_FULLNA
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coFullna;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.QUIC_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String quicCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.MARK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String mark;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.POST_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String postCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.COMM_ADDR
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String commAddr;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.ADDRESS
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String address;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.URL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String url;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.LINK_MAN
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String linkMan;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_CLERK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coClerk;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_LEADER
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coLeader;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.FI_LEADER
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String fiLeader;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.LOCA_TELE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String locaTele;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.DIRECTOR_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String directorCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.PARENT_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String parentCoCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.F_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String fCoCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.IS_USED
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String isUsed;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.F_ORG_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String fOrgCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.IS_SELF
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String isSelf;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.BANK_ACC
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String bankAcc;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.SHOP_CARD_NO
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String shopCardNo;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CORP_REPR
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String corpRepr;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.TRADE_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String tradeName;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.COUNTRY
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String country;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.PROVINCE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String province;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CITY
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String city;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.REAL_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String realCoCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.IS_LOWEST
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String isLowest;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.FINA_LEVEL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String finaLevel;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_KIND
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coKind;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.IS_PILOT
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String isPilot;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.IS_NEED_SEND_BANK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String isNeedSendBank;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.REGION_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String regionCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.TRANS_DATE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private Date transDate;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.IS_NEED_SEND_BANK_SL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String isNeedSendBankSl;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_TYPE_CODE_1
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coTypeCode1;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CAN_GETBILL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String canGetbill;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.GETBILL_ID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String getbillId;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CAN_CHARGE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String canCharge;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.TURN_IN_ACCT
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String turnInAcct;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.NT_ACC_ID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String ntAccId;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.NT_ACC_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String ntAccName;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.NT_HESUAN_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String ntHesuanCoCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.GUID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String guid;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.TRIGGER_ENABLE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private Short triggerEnable;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.PR_BI_COCODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String prBiCocode;

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_TYPE_CODE
   * @return  the value of MA_COMPANY.CO_TYPE_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoTypeCode() {
    return coTypeCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_TYPE_CODE
   * @param coTypeCode  the value for MA_COMPANY.CO_TYPE_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoTypeCode(String coTypeCode) {
    this.coTypeCode = coTypeCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.GB_CODE
   * @return  the value of MA_COMPANY.GB_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getGbCode() {
    return gbCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.GB_CODE
   * @param gbCode  the value for MA_COMPANY.GB_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setGbCode(String gbCode) {
    this.gbCode = gbCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_NAME
   * @return  the value of MA_COMPANY.CO_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoName() {
    return coName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_NAME
   * @param coName  the value for MA_COMPANY.CO_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoName(String coName) {
    this.coName = coName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_FULLNA
   * @return  the value of MA_COMPANY.CO_FULLNA
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoFullna() {
    return coFullna;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_FULLNA
   * @param coFullna  the value for MA_COMPANY.CO_FULLNA
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoFullna(String coFullna) {
    this.coFullna = coFullna;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.QUIC_CODE
   * @return  the value of MA_COMPANY.QUIC_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getQuicCode() {
    return quicCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.QUIC_CODE
   * @param quicCode  the value for MA_COMPANY.QUIC_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setQuicCode(String quicCode) {
    this.quicCode = quicCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.MARK
   * @return  the value of MA_COMPANY.MARK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getMark() {
    return mark;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.MARK
   * @param mark  the value for MA_COMPANY.MARK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setMark(String mark) {
    this.mark = mark;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.POST_CODE
   * @return  the value of MA_COMPANY.POST_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getPostCode() {
    return postCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.POST_CODE
   * @param postCode  the value for MA_COMPANY.POST_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.COMM_ADDR
   * @return  the value of MA_COMPANY.COMM_ADDR
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCommAddr() {
    return commAddr;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.COMM_ADDR
   * @param commAddr  the value for MA_COMPANY.COMM_ADDR
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCommAddr(String commAddr) {
    this.commAddr = commAddr;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.ADDRESS
   * @return  the value of MA_COMPANY.ADDRESS
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.ADDRESS
   * @param address  the value for MA_COMPANY.ADDRESS
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.URL
   * @return  the value of MA_COMPANY.URL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.URL
   * @param url  the value for MA_COMPANY.URL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.LINK_MAN
   * @return  the value of MA_COMPANY.LINK_MAN
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getLinkMan() {
    return linkMan;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.LINK_MAN
   * @param linkMan  the value for MA_COMPANY.LINK_MAN
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setLinkMan(String linkMan) {
    this.linkMan = linkMan;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_CLERK
   * @return  the value of MA_COMPANY.CO_CLERK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoClerk() {
    return coClerk;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_CLERK
   * @param coClerk  the value for MA_COMPANY.CO_CLERK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoClerk(String coClerk) {
    this.coClerk = coClerk;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_LEADER
   * @return  the value of MA_COMPANY.CO_LEADER
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoLeader() {
    return coLeader;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_LEADER
   * @param coLeader  the value for MA_COMPANY.CO_LEADER
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoLeader(String coLeader) {
    this.coLeader = coLeader;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.FI_LEADER
   * @return  the value of MA_COMPANY.FI_LEADER
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getFiLeader() {
    return fiLeader;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.FI_LEADER
   * @param fiLeader  the value for MA_COMPANY.FI_LEADER
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setFiLeader(String fiLeader) {
    this.fiLeader = fiLeader;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.LOCA_TELE
   * @return  the value of MA_COMPANY.LOCA_TELE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getLocaTele() {
    return locaTele;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.LOCA_TELE
   * @param locaTele  the value for MA_COMPANY.LOCA_TELE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setLocaTele(String locaTele) {
    this.locaTele = locaTele;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.DIRECTOR_CODE
   * @return  the value of MA_COMPANY.DIRECTOR_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getDirectorCode() {
    return directorCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.DIRECTOR_CODE
   * @param directorCode  the value for MA_COMPANY.DIRECTOR_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setDirectorCode(String directorCode) {
    this.directorCode = directorCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.PARENT_CO_CODE
   * @return  the value of MA_COMPANY.PARENT_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getParentCoCode() {
    return parentCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.PARENT_CO_CODE
   * @param parentCoCode  the value for MA_COMPANY.PARENT_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setParentCoCode(String parentCoCode) {
    this.parentCoCode = parentCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.F_CO_CODE
   * @return  the value of MA_COMPANY.F_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getfCoCode() {
    return fCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.F_CO_CODE
   * @param fCoCode  the value for MA_COMPANY.F_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setfCoCode(String fCoCode) {
    this.fCoCode = fCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.IS_USED
   * @return  the value of MA_COMPANY.IS_USED
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getIsUsed() {
    return isUsed;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.IS_USED
   * @param isUsed  the value for MA_COMPANY.IS_USED
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setIsUsed(String isUsed) {
    this.isUsed = isUsed;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.F_ORG_CODE
   * @return  the value of MA_COMPANY.F_ORG_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getfOrgCode() {
    return fOrgCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.F_ORG_CODE
   * @param fOrgCode  the value for MA_COMPANY.F_ORG_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setfOrgCode(String fOrgCode) {
    this.fOrgCode = fOrgCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.IS_SELF
   * @return  the value of MA_COMPANY.IS_SELF
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getIsSelf() {
    return isSelf;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.IS_SELF
   * @param isSelf  the value for MA_COMPANY.IS_SELF
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setIsSelf(String isSelf) {
    this.isSelf = isSelf;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.BANK_ACC
   * @return  the value of MA_COMPANY.BANK_ACC
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getBankAcc() {
    return bankAcc;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.BANK_ACC
   * @param bankAcc  the value for MA_COMPANY.BANK_ACC
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setBankAcc(String bankAcc) {
    this.bankAcc = bankAcc;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.SHOP_CARD_NO
   * @return  the value of MA_COMPANY.SHOP_CARD_NO
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getShopCardNo() {
    return shopCardNo;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.SHOP_CARD_NO
   * @param shopCardNo  the value for MA_COMPANY.SHOP_CARD_NO
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setShopCardNo(String shopCardNo) {
    this.shopCardNo = shopCardNo;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CORP_REPR
   * @return  the value of MA_COMPANY.CORP_REPR
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCorpRepr() {
    return corpRepr;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CORP_REPR
   * @param corpRepr  the value for MA_COMPANY.CORP_REPR
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCorpRepr(String corpRepr) {
    this.corpRepr = corpRepr;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.TRADE_NAME
   * @return  the value of MA_COMPANY.TRADE_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getTradeName() {
    return tradeName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.TRADE_NAME
   * @param tradeName  the value for MA_COMPANY.TRADE_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setTradeName(String tradeName) {
    this.tradeName = tradeName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.COUNTRY
   * @return  the value of MA_COMPANY.COUNTRY
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCountry() {
    return country;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.COUNTRY
   * @param country  the value for MA_COMPANY.COUNTRY
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.PROVINCE
   * @return  the value of MA_COMPANY.PROVINCE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getProvince() {
    return province;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.PROVINCE
   * @param province  the value for MA_COMPANY.PROVINCE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setProvince(String province) {
    this.province = province;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CITY
   * @return  the value of MA_COMPANY.CITY
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCity() {
    return city;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CITY
   * @param city  the value for MA_COMPANY.CITY
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.REAL_CO_CODE
   * @return  the value of MA_COMPANY.REAL_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getRealCoCode() {
    return realCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.REAL_CO_CODE
   * @param realCoCode  the value for MA_COMPANY.REAL_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setRealCoCode(String realCoCode) {
    this.realCoCode = realCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.IS_LOWEST
   * @return  the value of MA_COMPANY.IS_LOWEST
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getIsLowest() {
    return isLowest;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.IS_LOWEST
   * @param isLowest  the value for MA_COMPANY.IS_LOWEST
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setIsLowest(String isLowest) {
    this.isLowest = isLowest;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.FINA_LEVEL
   * @return  the value of MA_COMPANY.FINA_LEVEL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getFinaLevel() {
    return finaLevel;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.FINA_LEVEL
   * @param finaLevel  the value for MA_COMPANY.FINA_LEVEL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setFinaLevel(String finaLevel) {
    this.finaLevel = finaLevel;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_KIND
   * @return  the value of MA_COMPANY.CO_KIND
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoKind() {
    return coKind;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_KIND
   * @param coKind  the value for MA_COMPANY.CO_KIND
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoKind(String coKind) {
    this.coKind = coKind;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.IS_PILOT
   * @return  the value of MA_COMPANY.IS_PILOT
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getIsPilot() {
    return isPilot;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.IS_PILOT
   * @param isPilot  the value for MA_COMPANY.IS_PILOT
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setIsPilot(String isPilot) {
    this.isPilot = isPilot;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.IS_NEED_SEND_BANK
   * @return  the value of MA_COMPANY.IS_NEED_SEND_BANK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getIsNeedSendBank() {
    return isNeedSendBank;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.IS_NEED_SEND_BANK
   * @param isNeedSendBank  the value for MA_COMPANY.IS_NEED_SEND_BANK
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setIsNeedSendBank(String isNeedSendBank) {
    this.isNeedSendBank = isNeedSendBank;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.REGION_CODE
   * @return  the value of MA_COMPANY.REGION_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getRegionCode() {
    return regionCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.REGION_CODE
   * @param regionCode  the value for MA_COMPANY.REGION_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setRegionCode(String regionCode) {
    this.regionCode = regionCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.TRANS_DATE
   * @return  the value of MA_COMPANY.TRANS_DATE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public Date getTransDate() {
    return transDate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.TRANS_DATE
   * @param transDate  the value for MA_COMPANY.TRANS_DATE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setTransDate(Date transDate) {
    this.transDate = transDate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.IS_NEED_SEND_BANK_SL
   * @return  the value of MA_COMPANY.IS_NEED_SEND_BANK_SL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getIsNeedSendBankSl() {
    return isNeedSendBankSl;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.IS_NEED_SEND_BANK_SL
   * @param isNeedSendBankSl  the value for MA_COMPANY.IS_NEED_SEND_BANK_SL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setIsNeedSendBankSl(String isNeedSendBankSl) {
    this.isNeedSendBankSl = isNeedSendBankSl;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_TYPE_CODE_1
   * @return  the value of MA_COMPANY.CO_TYPE_CODE_1
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoTypeCode1() {
    return coTypeCode1;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_TYPE_CODE_1
   * @param coTypeCode1  the value for MA_COMPANY.CO_TYPE_CODE_1
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoTypeCode1(String coTypeCode1) {
    this.coTypeCode1 = coTypeCode1;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CAN_GETBILL
   * @return  the value of MA_COMPANY.CAN_GETBILL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCanGetbill() {
    return canGetbill;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CAN_GETBILL
   * @param canGetbill  the value for MA_COMPANY.CAN_GETBILL
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCanGetbill(String canGetbill) {
    this.canGetbill = canGetbill;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.GETBILL_ID
   * @return  the value of MA_COMPANY.GETBILL_ID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getGetbillId() {
    return getbillId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.GETBILL_ID
   * @param getbillId  the value for MA_COMPANY.GETBILL_ID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setGetbillId(String getbillId) {
    this.getbillId = getbillId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CAN_CHARGE
   * @return  the value of MA_COMPANY.CAN_CHARGE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCanCharge() {
    return canCharge;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CAN_CHARGE
   * @param canCharge  the value for MA_COMPANY.CAN_CHARGE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCanCharge(String canCharge) {
    this.canCharge = canCharge;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.TURN_IN_ACCT
   * @return  the value of MA_COMPANY.TURN_IN_ACCT
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getTurnInAcct() {
    return turnInAcct;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.TURN_IN_ACCT
   * @param turnInAcct  the value for MA_COMPANY.TURN_IN_ACCT
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setTurnInAcct(String turnInAcct) {
    this.turnInAcct = turnInAcct;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.NT_ACC_ID
   * @return  the value of MA_COMPANY.NT_ACC_ID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getNtAccId() {
    return ntAccId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.NT_ACC_ID
   * @param ntAccId  the value for MA_COMPANY.NT_ACC_ID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setNtAccId(String ntAccId) {
    this.ntAccId = ntAccId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.NT_ACC_NAME
   * @return  the value of MA_COMPANY.NT_ACC_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getNtAccName() {
    return ntAccName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.NT_ACC_NAME
   * @param ntAccName  the value for MA_COMPANY.NT_ACC_NAME
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setNtAccName(String ntAccName) {
    this.ntAccName = ntAccName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.NT_HESUAN_CO_CODE
   * @return  the value of MA_COMPANY.NT_HESUAN_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getNtHesuanCoCode() {
    return ntHesuanCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.NT_HESUAN_CO_CODE
   * @param ntHesuanCoCode  the value for MA_COMPANY.NT_HESUAN_CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setNtHesuanCoCode(String ntHesuanCoCode) {
    this.ntHesuanCoCode = ntHesuanCoCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.GUID
   * @return  the value of MA_COMPANY.GUID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getGuid() {
    return guid;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.GUID
   * @param guid  the value for MA_COMPANY.GUID
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setGuid(String guid) {
    this.guid = guid;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.TRIGGER_ENABLE
   * @return  the value of MA_COMPANY.TRIGGER_ENABLE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public Short getTriggerEnable() {
    return triggerEnable;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.TRIGGER_ENABLE
   * @param triggerEnable  the value for MA_COMPANY.TRIGGER_ENABLE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setTriggerEnable(Short triggerEnable) {
    this.triggerEnable = triggerEnable;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.PR_BI_COCODE
   * @return  the value of MA_COMPANY.PR_BI_COCODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getPrBiCocode() {
    return prBiCocode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.PR_BI_COCODE
   * @param prBiCocode  the value for MA_COMPANY.PR_BI_COCODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setPrBiCocode(String prBiCocode) {
    this.prBiCocode = prBiCocode;
  }
}