package com.ufgov.zc.common.commonbiz.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class MaCompanyKey implements Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = 7451955938719326548L;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private String coCode;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MA_COMPANY.ND
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  private BigDecimal nd;

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.CO_CODE
   * @return  the value of MA_COMPANY.CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public String getCoCode() {
    return coCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.CO_CODE
   * @param coCode  the value for MA_COMPANY.CO_CODE
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setCoCode(String coCode) {
    this.coCode = coCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MA_COMPANY.ND
   * @return  the value of MA_COMPANY.ND
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public BigDecimal getNd() {
    return nd;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MA_COMPANY.ND
   * @param nd  the value for MA_COMPANY.ND
   * @ibatorgenerated  Tue Jul 09 02:33:33 CST 2013
   */
  public void setNd(BigDecimal nd) {
    this.nd = nd;
  }
}